-- MySQL Script generated by MySQL Workbench
-- 04/19/16 14:56:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`transformando`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transformando` (
  `idTransformando` INT NOT NULL AUTO_INCREMENT,
  `nomeTransformando` VARCHAR(45) NOT NULL,
  `emailTransformando` VARCHAR(45) NOT NULL,
  `rgTransformando` VARCHAR(35) NOT NULL,
  `cpfTransformando` VARCHAR(45) NOT NULL,
  `nascTransformando` DATE NULL,
  `idadeTransformando` DECIMAL(3) NULL,
  `igrejaTransformando` VARCHAR(45) NULL,
  `cepTransformando` VARCHAR(45) NULL,
  `endTransformando` VARCHAR(45) NULL,
  `bairroTransformando` VARCHAR(100) NULL,
  `cidadeTransformando` VARCHAR(45) NULL,
  `ufTransformando` VARCHAR(2) NULL,
  `tipoPgto` VARCHAR(45) NULL,
  PRIMARY KEY (`idTransformando`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`apoio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`apoio` (
  `idApoio` INT NOT NULL AUTO_INCREMENT,
  `nomeApoio` VARCHAR(45) NULL,
  `emailApoio` VARCHAR(45) NULL,
  `rgApoio` VARCHAR(45) NULL,
  `cpfApoio` VARCHAR(45) NULL,
  `nascApoio` DATE NULL,
  `idadeApoio` VARCHAR(45) NULL,
  `igrejaApoio` VARCHAR(45) NULL,
  `cepApoio` VARCHAR(45) NULL,
  `endApoio` VARCHAR(45) NULL,
  `bairroApoio` VARCHAR(45) NULL,
  `cidadeApoio` VARCHAR(45) NULL,
  `ufApoio` VARCHAR(2) NULL,
  `tipoPgto` VARCHAR(45) NULL,
  `versaoTF` VARCHAR(45) NULL,
  PRIMARY KEY (`idApoio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`senha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`senha` (
  `senha` VARCHAR(100) NOT NULL,
  `idTransformando` INT NOT NULL,
  `idApoio` INT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
